### PR TITLE
*: ShellCheck fixes

### PR DESCRIPTION
**Pull request by travier**
May look benign but need careful review.

Part of fixes for https://github.com/coreos/repo-templates/pull/39.

### CODE REVIEW

**Comment by travier** [comment]
Ping @runcom for review.

**Comment by travier** [comment]
The C9S test timed out 😕

**Comment by runcom** [comment]
@henrywang do you know why tests failed/timeout

**Comment by runcom** [comment]
> @henrywang do you know why tests failed/timeout

our QE is taking care of this

**Comment by runcom** [comment]
@travier can you rebase? tests should turn green afterwards

**Review by runcom — APPROVED** [review]

**Pull request merged**
