### PR TITLE
feat: run coi with --ignition* flags if provided

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <antoniomurdaca@gmail.com>

### CODE REVIEW

**Comment by runcom** [comment]
@7flying we can trigger tests here from your osbuild-composer PR too before merging this :)

**Comment by henrywang** [comment]
@runcom @7flying My fix works.

**Comment by runcom** [comment]
@7flying is this ready to go from your side of the story? :)

**Comment by 7flying** [comment]
> @7flying is this ready to go from your side of the story? :)

Yes it is :+1:

**Pull request merged**
